Content-Type: multipart/mixed; boundary="===============0199087865740087946=="
MIME-Version: 1.0
Message-ID: 304c75e0-2ddc-435c-be21-3bd7e3d26ada@example.com
Date: Fri, 24 Nov 2023 22:58:18 +0700
To: example@example.com
Cc: 
From: Mang may tinh <example@example.com>
Subject: qwerqwerwqer

--===============0199087865740087946==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

qwerqerqwrqwr
--===============0199087865740087946==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/x-python
Content-Disposition: attachment; filename="thu.py"

I1Thur90IGhpaGkK

--===============0199087865740087946==--

.

