Content-Type: multipart/mixed; boundary="===============7486063670520727911=="
MIME-Version: 1.0
Message-ID: 37c644e1-5e16-4c84-81a2-be36d28bdbb3@example.com
Date: Sun, 26 Nov 2023 18:29:10 +0700
To: thiec ,thu
From: Mang may tinh <example@example.com>
Subject: =?utf-8?b?w6FkZsOhZGbDoWRm?=

--===============7486063670520727911==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

w6FkZnNhZGbDoWRmc8SRZMOhYWY=

--===============7486063670520727911==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/x-python
Content-Disposition: attachment;
 filename="/Users/luonggiathiec/Desktop/MMT/DO-AN-SOCKET/thu.py"

I1Thur90IGhpaGkK

--===============7486063670520727911==--

.

