Content-Type: multipart/mixed; boundary="===============3326288457478794452=="
MIME-Version: 1.0
Message-ID: c905fadb-2ad5-437f-b70d-2f1bd0f81a06@example.com
Date: Fri, 24 Nov 2023 22:15:36 +0700
To: giathiec@gmail.com
Cc: example@example.com
From: Mang may tinh <example@example.com>
Subject: kokokok

--===============3326288457478794452==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

aoaoaoao
--===============3326288457478794452==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/x-python
Content-Disposition: attachment; filename="thu.py"

I1Thur90IGhpaGkK

--===============3326288457478794452==--

.

