Content-Type: multipart/mixed; boundary="===============4376013900266882267=="
MIME-Version: 1.0
Message-ID: 57fc3c7f-56ac-4fff-98f2-7748110f866e@example.com
Date: Fri, 24 Nov 2023 22:57:31 +0700
To: example@example.com
Cc: giathiec@gmail.com
From: Mang may tinh <example@example.com>
Subject: asdfasdfasdfasdf

--===============4376013900266882267==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

asdfasdfadscadsasdcasdcasdcsad
--===============4376013900266882267==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/x-python
Content-Disposition: attachment; filename="thu.py"

I1Thur90IGhpaGkK

--===============4376013900266882267==--

.

