Content-Type: multipart/mixed; boundary="===============2749998747837543607=="
MIME-Version: 1.0
Message-ID: 66a6bb54-6501-4d25-9885-a4118e86c0e0@example.com
Date: Fri, 24 Nov 2023 23:01:53 +0700
To: example@example.com
From: Mang may tinh <example@example.com>
Subject: 12341234

--===============2749998747837543607==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

1234
--===============2749998747837543607==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/x-python
Content-Disposition: attachment; filename="thu.py"

I1Thur90IGhpaGkK

--===============2749998747837543607==--

.

