+OK 400
Message-ID: <1db5c15d-8b15-4313-98fc-0bc467e53e9c@gmail.com>
Date: Wed, 15 Nov 2023 16:13:25 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: example@example.com
From: Ta Minh Thu <taminhthunkh@gmail.com>
Subject: Test nhieu dong hon
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit
X-EsetId: 37303A297F03045A647162

Test

Nhieu

Dong

Hon

.
