Content-Type: multipart/mixed; boundary="===============6899204588135300138=="
MIME-Version: 1.0
Message-ID: 0ab160f9-aa86-4a9c-904e-8492666e3ea8@example.com
Date: Fri, 24 Nov 2023 21:29:02 +0700
To: example@example.com
Cc: giathiec@giathiec.com
From: Mang may tinh <example@example.com>
Subject: TEST

--===============6899204588135300138==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

TEST TEST TEST
--===============6899204588135300138==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/x-python
Content-Disposition: attachment;
 filename*=utf-8''C%3A%5CUsers%5CAdmins%5CDesktop%5CM%E1%BA%A1ng%20m%C3%A1y%20t%C3%ADnh%5C%C4%90%E1%BB%92%20%C3%81N%20SOCKET%5Cthu.py

I1Thur90

--===============6899204588135300138==--

.
