Message-ID: <afad2b87-16ea-4a8b-af0d-450c2061fa87@gmail.com>
Date: Wed, 15 Nov 2023 15:18:09 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: vi-x-KieuCu.[Chuan]
To: example@example.com
Cc: giathiecluong123@gmail.com
From: Luong Gia Thiec <giathiecluong123@gmail.com>
Subject: cc
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

cc


.
