Content-Type: multipart/mixed; boundary="===============6175100668688526528=="
MIME-Version: 1.0
Message-ID: a8f79a28-20a5-4191-b66b-ed3f24bcdba6@example.com
Date: Mon, 27 Nov 2023 11:02:11 +0700
To: example@example.com
Cc: giathiec
From: Mang may tinh <example@example.com>
Subject: 123

--===============6175100668688526528==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

123
--===============6175100668688526528==--

.

