Content-Type: multipart/mixed; boundary="===============2658504347207667401=="
MIME-Version: 1.0
Message-ID: 77189079-49fe-449a-9edc-83dd744867b0@example.com
Date: Sun, 26 Nov 2023 12:53:28 +0700
To: example@example.com
From: Mang may tinh <example@example.com>
Subject: test file attachment

--===============2658504347207667401==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

test file txt
--===============2658504347207667401==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment; filename="array.txt"

MQ0KMg0KMw0KNA0KNQ0K

--===============2658504347207667401==--

.

