Content-Type: multipart/mixed; boundary="===============2746551557927821265=="
MIME-Version: 1.0
Message-ID: f88545d5-7326-416e-83f1-95b283d477a4@example.com
Date: Thu, 23 Nov 2023 10:52:45 +0700
To: example@example.com
From: Mang may tinh <example@example.com>
Subject: kk

--===============2746551557927821265==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

kkkk
--===============2746551557927821265==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment; filename="input"

aGVoZQo=

--===============2746551557927821265==--

.
