Content-Type: multipart/mixed; boundary="===============2757545462068496888=="
MIME-Version: 1.0
Message-ID: 7a99af30-3b18-422f-9bc7-ae49ad6f31ab@example.com
Date: Tue, 28 Nov 2023 15:19:20 +0700
To: example@example.com
Cc: thiec
From: Mang may tinh <example@example.com>
Subject: 11111111

--===============2757545462068496888==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

111111111111
--===============2757545462068496888==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: txt/None
Content-Disposition: attachment; filename="input.txt"

YTthYWFzZGFkYXNkYWRhc2RhZGFzZGFka3ZqZnNkbGt2anNkbGZ2a2phd2Vpb3JqYWVmamF3b2ll
dmphdm5ka25jYXNsZGtmanNhbGZr

--===============2757545462068496888==--

.

