Content-Type: multipart/mixed; boundary="===============6979017937719408519=="
MIME-Version: 1.0
Message-ID: 4ace5b70-c0b7-417d-8af7-bfe348648a47@example.com
Date: Tue, 28 Nov 2023 15:30:20 +0700
To: example@example.com
Cc: alo
From: Mang may tinh <example@example.com>
Subject: l

--===============6979017937719408519==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

l
--===============6979017937719408519==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: txt/None
Content-Disposition: attachment; filename="input.txt"

YTthYWFzZGFkYXNkYWRhc2RhZGFzZGFka3ZqZnNkbGt2anNkbGZ2a2phd2Vpb3JqYWVmamF3b2ll
dmphdm5ka25jYXNsZGtmanNhbGZr

--===============6979017937719408519==--

.

