Message-ID: <0e0a1b3c-4c43-49a5-a7f9-209f0800f5f3@gmail.com>
Date: Thu, 23 Nov 2023 14:34:41 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: vi-x-KieuCu.[Chuan]
To: example@example.com
Cc: giathiec@gmail.com
From: Luong Gia Thiec <giathiecluong123@gmail.com>
Subject: loldalat
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

loldalat


.

